apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: apache-spark-argo-workflows
  title: Apache Spark Application with Argo Workflows
  description: Creates an Apache Spark Application with Argo Workflows
spec:
  owner: guest
  type: job
  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in some steps
      required:
        - name
        - owner
      properties:
        name:
          title: Application Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
        namespace:
          title: Namespace
          type: string
          default: default
          description: Namespace to deploy this application into. Optional. Defaults to application name.
          ui:options:
            rows: 5
    - title: Paste your Spark manifest
      required:
        - manifest
      properties:
        manifest:
          type: string
          description: 'Paste your Spark Application manifest here'
          "ui:widget": "textarea"
          "ui:options": {
            "inputType": "data",
            "rows": 15
          }
          ui:autofocus: true
          "ui:placeholder": |
            apiVersion: "sparkoperator.k8s.io/v1beta2"
            kind: SparkApplication
            metadata:
              name:
            spec:
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./templates/SparkManifest
        values:
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          clusterName: 'cnoe-packaging'
    - id: write
      name: write-to-file
      action: roadiehq:utils:fs:write
      input:
        path: input.yaml
        content: ${{ parameters.manifest }}
    - id: parse
      name: deserialize
      action: roadiehq:utils:fs:parse
      input:
        path: input.yaml
        parser: yaml
    - id: merge
      name: Merge
      action: roadiehq:utils:json:merge
      input:
        path: merge.json
        content: ${{ steps.parse.output.content }}
    - id: deserialise
      name: deserialize manifest
      action: roadiehq:utils:fs:parse
      input:
        path: 'merge.json'
        parser: 'json'
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./templates/ArgoWorkflowsManifest
        values:
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          clusterName: 'cnoe-packaging'
          manifest: ${{ steps.deserialise.output.content }}
    - id: apply
      name: apply manifest
      action: cnoe:kubernetes:apply
      input:
        manifestPath: manifest.yaml
        namespaced: true
        clusterName: "cnoe-packaging"
    - id: create-repo
      name: Create Repository
      action: github:repo:create
      input:
        repoUrl: github.com?repo=spark-ui-${{parameters.name}}&owner=manabuOrg
    - id: init-repo
      name: Initialize Repository
      action: github:repo:push
      input:
        repoUrl: github.com?repo=spark-ui-${{parameters.name}}&owner=manabuOrg
        defaultBranch: main
    - id: register
      name: Register
      action: catalog:register
      input:
        catalogInfoPath: '/catalog-info.yaml'
        repoContentsUrl: ${{ steps['init-repo'].output.repoContentsUrl }}
  output:
    links:
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
