---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  annotations:
    backstage.io/kubernetes-id: "${{values.clusterName}}"
    apache-spark.cnoe.io/cluster-name: "${{values.clusterName}}"
    argo-workflows.cnoe.io/cluster-name: "${{values.clusterName}}"
    backstage.io/kubernetes-namespace: "${{values.namespace}}"
    backstage.io/kubernetes-label-selector: "backstage.io/component-id=${{values.name}}"
spec:
  type: job
  lifecycle: experimental
  owner: ${{ values.owner | default('guest')}}
