---
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "ui-${{values.name}}"
  namespace: ${{values.namespace | dump}}
  labels:
    backstage.io/component-id: ${{values.name | dump}}
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "${{values.params.image}}"
  mainApplicationFile: "${{values.params.mainFile}}"
  sparkVersion: "${{values.params.sparkVersion}}"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: ${{values.params.driverCores | default(1)}}
    memory: "${{values.params.driverMemory | default("512m")}}"
    labels:
      version: ${{values.params.sparkVersion}}
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: ${{values.params.executorCores | default(1)}}
    instances: ${{values.params.executorInstances | default(1)}}
    memory: ${{values.params.executorMemory | default("512m")}}
    labels:
      version: ${{values.params.sparkVersion}}
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
